### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.springframework.web.method.support.CompositeUriComponentsContributor

### ISSUE THREAD

**Issue by Jason1220** [handuyishe/dubbo-monitor#23]
运行报错：
Caused by: java.lang.ClassNotFoundException: org.springframework.web.method.support.CompositeUriComponentsContributor

**Comment by chenzhiguo** [comment]
启动时找不到CompositeUriComponentsContributor这个class，我看了下，这个class在spring4里面才有，因为我们当时的Dubbo是改成Spring4.1.6后再变异的，所以没发现这个问题。能详细点说一下，是哪个地方用到这个类了吗？

**Comment by Mrwb** [comment]
我也遇到同样的问题了，我直接clone了项目mvn build下，启动就报这个错误。mongo分支

**Comment by chenzhiguo** [comment]
可将项目Spring版本该问Spring4.1.6试试。

**Comment by Mrwb** [comment]
这个是4.1.6release版。我用majinka自己分支的可以搞定了，不纠结了

**Comment by tianyi2013** [comment]
加一个spring-web的依赖就行了
