### ISSUE TITLE
js new Date()的浏览器兼容性

### ISSUE THREAD

**Issue by songzhongkai** [handuyishe/dubbo-monitor#3]
ff，ie，safari无法将 yyyy-MM-dd HH:mm:ss格式的string转换成Date，会报invalid Date，chrome没有问题。
但是都可以将 yyyy/MM/dd HH:mm:ss转换成Date，建议时间那里，由

new Date($('#invokeDateFrom').val() + ' 00:00:00')  
改成
new Date($('#invokeDateFrom').val().replace(new RegExp("-","gm"),"/") + ' 00:00:00'),

**Comment by chenzhiguo** [comment]
感谢您的贡献，代码已更新。同时期待您更多的支持！
