### ISSUE TITLE
在mongodb 3.0.7环境下报错

### ISSUE THREAD

**Issue by luohoufu** [handuyishe/dubbo-monitor#5]
Caused by: java.lang.NoClassDefFoundError: org/springframework/objenesis/ObjenesisStd

**Comment by majinkai** [comment]
是Spring版本的问题，这个类在Spring4中存在

**Comment by majinkai** [comment]
是Spring版本的问题，这个类在Spring4中存在

**Comment by luohoufu** [comment]
那为什么pom中不更新到Spring4,不过后我自已改到Spring4可以运行了。目前dubbo服务用了2.5.3，也用了dubbox

**Comment by majinkai** [comment]
dubbo 2.5.3用的是spring2
